main: com.cavetale.serverstatus.ServerStatusPlugin
name: ServerStatus
version: 0.1
api-version: 1.13
description: ServerStatus Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  serverstatus:
    description: ServerStatus Command
    permission: serverstatus.serverstatus
    permission-message: You do not have permission!
    usage: /<command>
permissions:
  serverstatus.serverstatus:
    description: Use /serverstatus
    children:
      serverstatus.child: true
