main: com.winthier.serverstatus.ServerStatusPlugin
name: ServerStatus
version: 0.1
description: ServerStatus Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  serverstatus:
    description: Debug interface
    permission: serverstatus.serverstatus
    usage: |-
      /serverstatus load|save|update
      /serverstatus on|off <server>
permissions:
  serverstatus.serverstatus:
    description: Use /serverstatus
